# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm4350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter dre9,$(TARGET_DEVICE)),)

endif
